[tool.poetry]
name = "robotcode"
version = "0.0.1"
description = ""
authors = ["Daniel Biehl <daniel.biehl@imbus.de>"]

[tool.poetry.dependencies]
python = "^3.8"
robotframework = "^3.2.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.790"
flake8 = "^3.8.4"
black = "^20.8b1"
pep8-naming = "^0.11.1"
pycodestyle = "^2.6.0"
autopep8 = "^1.5.4"
pylint = "^2.6.0"
debugpy = "^1.2.0"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.poetry-dynamic-versioning.substitution]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

