[tool.poetry]
name = "robotcode"
version = "0.0.1"
description = ""
authors = ["Daniel Biehl <daniel.biehl@imbus.de>"]
include = ["robotcode/py.typed", "README.md"]

[tool.poetry.dependencies]
python = "^3.8"
black = "^20.8b1"
pydantic = "^1.7.3"


[tool.poetry.dev-dependencies]
robotframework = "^3.2.2"
pytest = "^5.2"
mypy = "^0.790"
flake8 = "^3.8.4"
black = "^20.8b1"
pep8-naming = "^0.11.1"
pycodestyle = "^2.6.0"
autopep8 = "^1.5.4"
pylint = "^2.6.0"
debugpy = "^1.2.0"
rope = "^0.18.0"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.poetry-dynamic-versioning.substitution]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project    
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | out
  )/  
)
'''