[tool.poetry]
name = "robotcode"
version = "0.4.10"
description = "Language server,debugger and tools for RobotFramework"
authors = ["Daniel Biehl <daniel.biehl@imbus.de>"]
homepage = 'https://github.com/d-biehl/robotcode'
repository = 'https://github.com/d-biehl/robotcode'
readme = "README.md"
license = "Apache-2.0"
include = ["robotcode/py.typed", "README.md"]
exclude = ["robotcode/external"]
keywords = [
  "Testing",
  "RobotFramework",
  "Keyword Driven",
  "Language Server Protocol",
  "Visual Studio Code",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: Apache Software License",
  "Framework :: Robot Framework",
  "Framework :: Robot Framework :: Tool",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: Implementation",
  "Topic :: Software Development :: Testing",
  "Topic :: Software Development :: Testing :: Acceptance",
  "Topic :: Software Development :: Testing :: BDD",
  "Typing :: Typed",
  "Topic :: Software Development :: Debuggers",
  "Topic :: Text Editors :: Integrated Development Environments (IDE)",

]

[tool.poetry.dependencies]
python = "^3.8"
robotframework = "^4.0.0"


[tool.poetry.dev-dependencies]
isort = "^5.9.2"
mypy = "^0.910"
flake8 = "^3.9.2"
black = "^21.6b0"
pep8-naming = "^0.12.0"
debugpy = "^1.3.0"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
pytest-cov = "^2.12.1"
coverage = "^5.5"
coloredlogs = "^15.0.1"
robotremoteserver = "^1.1"
Cython = "^0.29.24"
robotframework-robocop = "^1.7.1"
robotframework-tidy = "^1.5.1"
PyYAML = "^6.0"
types-PyYAML = "^6.0"
snakeviz = "^2.1.1"
pytest-regressions = "^2.3.1"


[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
style = "semver"

[tool.poetry-dynamic-versioning.substitution]
files = ["*/_version.py", "package.json"]

patterns = [
  "(^__version__\\s*=\\s*['\\\"])[^'\\\"]*(['\\\"])",
  "(\\\"version\\\"\\s*:\\s*['\\\"])[0-9]+[^'\\\"]*(['\\\"])",
]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project    
    | \.mypy_cache
    | \.tox
    | \.venv    
    | build
    | dist
    | out
    | robotcode/external
  )/  
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -vv"
filterwarnings = "ignore:.*Using or importing the ABCs from 'collections' instead of from 'collections.abc'.*:DeprecationWarning"
testpaths = ["tests"]
junit_suite_name = "robotcode"
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(levelname)s %(name)s: %(message)s"

[tool.isort]
profile = "black"
src_paths = ["robotcode", "tests"]
skip_gitignore = true
skip = ['external']

[tool.coverage.run]
omit = ["*tests*"]
source = ["robotcode"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "if __name__ == .__main__.:",
  "raise NotImplementedError",
]
fail_under = 40

[tool.mypy]
# MyPy config
# File reference here - http://mypy.readthedocs.io/en/latest/config_file.html#config-file
python_version = 3.8
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
strict = true
disallow_subclassing_any = false
ignore_missing_imports = true
