[tool.poetry]
name = "robotcode"
version = "0.1.0"
description = ""
authors = ["Daniel Biehl <daniel.biehl@imbus.de>"]

[tool.poetry.dependencies]
python = "^3.8"
robotframework = "^3.2.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.790"
flake8 = "^3.8.4"
black = "^20.8b1"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

