[tool.poetry]
name = "robotcode"
version = "0.1.0-alpha.1"
description = ""
authors = ["Daniel Biehl <daniel.biehl@imbus.de>"]
include = ["robotcode/py.typed", "README.md"]
exclude = ["robotcode/external"]

[tool.poetry.dependencies]
python = "^3.8"
robotframework = "^3.2.2"
robotframework-robocop = "^1.5.0"

[tool.poetry.dev-dependencies]
mypy = "^0.790"
flake8 = "^3.8.4"
black = "^20.8b1"
pep8-naming = "^0.11.1"
pycodestyle = "^2.6.0"
autopep8 = "^1.5.4"
pylint = "^2.6.0"
debugpy = "^1.2.0"
rope = "^0.18.0"
pytest-asyncio = "^0.14.0"
pytest = "^6.2.1"
coloredlogs = "^15.0"
robotremoteserver = "^1.1"
Cython = "^0.29.22"
pydantic = "^1.7.3"
isort = "^5.7.0"
pytest-cov = "^2.11.1"
coverage = { extras = ["toml"], version = "^5.5" }

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.poetry-dynamic-versioning.substitution]
files = ["*/_version.py", "package.json"]

patterns = [
  "(^__version__\\s*=\\s*['\\\"])[^'\\\"]*(['\\\"])",
  "(\\\"version\\\"\\s*:\\s*['\\\"])[^'\\\"]*(['\\\"])",
]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project    
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | out
    | robotcode/external
  )/  
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -vv"
filterwarnings = "ignore:.*Using or importing the ABCs from 'collections' instead of from 'collections.abc'.*:DeprecationWarning"
testpaths = ["tests"]
junit_suite_name = "robotcode"

[tool.isort]
profile = "black"
src_paths = ["robotcode", "tests"]
skip_gitignore = true
skip = ['external']
