[tool.poetry]
name = "robotcode"
version = "0.2.0"
description = "Language server,debugger and tools for RobotFramework"
authors = ["Daniel Biehl <daniel.biehl@imbus.de>"]
include = ["robotcode/py.typed", "README.md"]
exclude = ["robotcode/external"]

[tool.poetry.dependencies]
python = "^3.8"
robotframework = "^4.0.0"


[tool.poetry.dev-dependencies]
pydantic = "^1.8.2"
isort = "^5.9.2"
mypy = "^0.910"
flake8 = "^3.9.2"
black = "^21.6b0"
pep8-naming = "^0.12.0"
debugpy = "^1.3.0"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
pytest-cov = "^2.12.1"
coverage = "^5.5"
coloredlogs = "^15.0.1"
robotremoteserver = "^1.1"
Cython = "^0.29.24"
robotframework-robocop = "^1.7.1"


[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.poetry-dynamic-versioning.substitution]
files = ["*/_version.py", "package.json"]

patterns = [
  "(^__version__\\s*=\\s*['\\\"])[^'\\\"]*(['\\\"])",
  "(\\\"version\\\"\\s*:\\s*['\\\"])[^'\\\"]*(['\\\"])",
]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project    
    | \.mypy_cache
    | \.tox
    | \.venv    
    | build
    | dist
    | out
    | robotcode/external
  )/  
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -vv"
filterwarnings = "ignore:.*Using or importing the ABCs from 'collections' instead of from 'collections.abc'.*:DeprecationWarning"
testpaths = ["tests"]
junit_suite_name = "robotcode"

[tool.isort]
profile = "black"
src_paths = ["robotcode", "tests"]
skip_gitignore = true
skip = ['external']
